version: '3'
volumes:
  mysql_data:
services:
  mysql:
    image: mysql:5.7
    volumes:
      - 'mysql_data:/var/lib/mysql'
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'company'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: mysqld --max-connections=1000 --sql-mode=""
